insert into users values ('rentzso', 'renzo frigato', 'belloeimpossibil');
insert into users values ('juliavc', 'julia viladomat', 'bellatroppobella');
insert into users (username, apikey) values ('sconosciuto', 'echiloconoscelui');
insert into users (username, apikey) values ('papadirenzo', 'eilpapadirenzono');
insert into tweets values ( 1, 'rentzso', 'julia I love you :)', sysdate());
insert into tweets values ( 2, 'juliavc', 'renzo I love you :)', sysdate());
insert into tweets values ( 3, 'sconosciuto', 'renzo, julia who are they?', sysdate());
insert into tweets values ( 4, 'papadirenzo', 'I am renzo\'s father', sysdate());
--insert into followers values ('rentzso', 'juliavc');
--insert into followers values ('rentzso', 'papadirenzo');
--insert into followers values ('juliavc', 'rentzso');